################################################################
# Global configuration
################################################################
[global]
checkNewVersion = false
sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[entryPoints.websecure.transport.respondingTimeouts]
readTimeout = "600s"
idleTimeout = "600s"
writeTimeout = "600s"

[certificatesResolvers]
[certificatesResolvers.myresolver.acme]
email = "matthias@emdemail.de"
storage = "/certs/acme.json"

[certificatesResolvers.myresolver.acme.tlsChallenge]

################################################################
# Service configuration
################################################################

# Traefik logs
[log]

# Log level
level = "WARN"

# Enable API and dashboard
[api]
insecure = true

# Enable docker
[providers.docker]
network = "traefik"
exposedByDefault = false


################################################################
# Plugins
################################################################
[experimental.plugins.bouncer]
moduleName = "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
version = "v1.6.0"

################################################################
# Load additional middlewares
################################################################
[providers.file]
directory = "/etc/traefik/dynamic"
watch = true
