{
	"data": "ENC[AES256_GCM,data:DAx21rdlmf4h8ZjJ3b6SqjCETOodVyBRVGLWKpI73Z7guMCaI6ykTTmYAe8g6y7f9W/wiL0OLkBqo9v/C5iUqZxxiEb5BOTeMluFQOpejRzsL92PlZy/I1BNdUJoqb0jDdn5RZWMkx71xi39NvPotVm1GCYjYrK1Z8andiORb1K+srqKp9hfsi6TC3Iq9bRAkNALX0IqqDneBE8AfHGBGia2J/GEBxRdQEmpAQ/9+XIWy3wcxX2IoF+YhGbGJSyzWq9trM4mKifM3WS04vHsrGFip2sbhd9yKHld5bt1/Ut0Iy0fTsdLhDs3PiZo0PDqiOfAaRdf2WSB8YiJti2xG6ckfWjHptN5a0/BlMItVMQhsXScvlHy7g99q1bB1yd8+WIIbaFNHD+6z2c1b6SIeP16jtL0GKrsdtsfxcQ37x+tRCILM5WViDGlotkW7GiXYwiNv49kZsH+ic/7nfNlyOA+FxN78VjcNJIc3QGDOeKk4VOn4Ws3sqDuBTGpi0d1/yttz1QVTSQClkGIw5s8p8Uzmy6hX4cfh3IkrFjZhRC7bWt6HzLu51BI9ak87yqo/ynP6ddlhg==,iv:64jYI8zkmeCH596XOAlVXCvEQoEChmqvU5rzf8KPj+8=,tag:2JcbhrpQorYVj9vJWfAJ3g==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG51MlkydyBBMnNoeDlC\nMWdzZk1VMDhxVFpOc3gxZ21oZk9XeTMxNHp6bHNVNENnbVhFVQp1bHRTK1djczFt\nYUIvOVg1V0xFNzJzRGVUUXZ3VEk1b2w2OUY2TmNKOXRFCi0tLSBPZy95U1FkOTUz\nZ2tEaHNrK2VRRXQyMm80N0dSbHd1d2c2cEJEeGRpNDNRCgcDyNpxfwphgTS8FJqc\nWpgUN154NFgtCiS65g0bgfNvhVx6eHtt6ARB46FdDZ04IlxOFOI9bkdabWqRfGlg\n5dE=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qfxert3c6e83vk20ggq70r22pkvu3636cslf4kxa5gdrj900hqf2qaxhcfa"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vi9nUlA3SXNBalVRZTdh\ndUlHWnBiblFKQ2YxSkxqTGhtaVdvQVJTTUY4CllHU0xISFZGeE5ZbmIxNFhURFNl\nN3FKNzY0MU1qcmNRSVpVV3JnR1FjR3cKLS0tIFlNTjVNSzdOTkpib3JPY0g5U1Qz\nM2doTSs0cVZUMnc2V2M1R2sxTVNia3cKvMPg3fY0vZ4lkJhQcIfgMdJTJWEhtIr4\nwgbLqK07OWVoCd0lwJz/IzN0ParfzQ2f1COyj3APRgya7neuHnxHiA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1zllz3l3z9vqvvdwdch3yutfz8t3lxqg4gxnsg9urjdj0ejlax32qcaatky"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SXBDSjFKMDBKWWkxblJM\ndjJIWTZVdVRjWGxieDNyVEpxTEhoRkxUQ2tzCnExcTRLOGxnUWZkWlFiNEdURGZV\nWkJYcEtwZHA1NkUyVHNaTmRUYW1NaVEKLS0tIG4wTVNxOE1sQnF4bXRXallxVTdV\nN0tPK0dOWFllWDhyemxmaHZ3Z2xZQkEKUp5BOBvoK+wefoIqhugz9fryz8oo8SvP\n6ubSi0AZeYPqonABzO+aJ9Zr/KjsqeWvRGcp7dMkYyMb7MNU2HoTxw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1hwxs9ywdr7s8kpx9lvjn77fv8ylcchrjpzsq2txaqlnu5zrtj4xq7wjhtu"
			}
		],
		"lastmodified": "2026-06-23T19:17:13Z",
		"mac": "ENC[AES256_GCM,data:ZjpaX4G2Xt9ecLwRJyLv24Km2ScMYMt7cG06vyVPVMnZdo5rKZxsCuaZXYJj63bAyn++w69gGEjXzXT5xb5PWw4pOgrs8zjV9nzcxufoHCsP1hMQE39GEgZhA3yqT+39UxmvlTeVKeK0nIiu14ozPlFrKxKuQpclE9Ze2zMVCgs=,iv:FPFADUkaPO1lIH3UzZyS4DUiMY6YRecBMf2hJrOQZrM=,tag:hiUvpmrFEKcFmztREHgWaA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.1"
	}
}
