serverAddr = "vps.emdecloud.de"
serverPort = 7000

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

transport.wireProtocol = "v2"

[[proxies]]
name = "bartok-traefik-tcp"
type = "tcp"
localIP = "traefik--server"
localPort = 443
remotePort = 9443
